version: "3" 
services:
  app:
    container_name: react-app-prod
    image: react-app-prod
    build:
      context: ./actcept
      dockerfile: Dockerfile
    ports: 
      - 3000:3000
    
  api:
    container_name: api_actcept
    build: 
      context: ./actcept-api
      dockerfile: Dockerfile
    depends_on:
      - database
    ports:
      - 3001:3001
    environment:
      - DB_HOSTNAME=myTestPostgres2
      - DB_PASSWORD=mysecretpassword

       # - database
   # environment:
     # - DB_HOSTNAME=gigstr
     # - DB_PASSWORD=gigstr

  database:
    image: postgres:latest
    container_name: myTestPostgres2
    environment:
      - POSTGRES_PASSWORD=mysecretpassword
    ports:
      - 5432:5432

  #database:
    #image: khaashifriaz/gigstr:gigtag   
    #container_name: "gigstr-db-container"
    #environment:
      #- POSTGRES_PASSWORD=gigstr
    #ports:
      #- 5432:5432

# docker run --name my-postgres -p 5432:5432 -e POSTGRES_PASSWORD=mysecretpassword -d postgres