version: "3"
services:
  react1:
    container_name: react1
    image: react1
    build:
      context: ./actcept
      dockerfile: Dockerfile
    ports:
      - 5001:3000

  api1:
    container_name: api1
    build:
      context: ./actcept-api
      dockerfile: Dockerfile
    depends_on:
      - database
    ports:
      - 3001:3000
    environment:
      - DB_HOSTNAME=gigstr-db-container
      - DB_PASSWORD=gigstr

  database:
    image: khaashifriaz/gigstr:gigtag
    container_name: gigstr-db-container
    environment:
      - POSTGRES_PASSWORD=gigstr
    ports:
      - 5432:5432

  # database:

  #   image: postgres:latest

  #   container_name: myTestPostgres2

  #   environment:

  #     - POSTGRES_PASSWORD=mysecretpassword

  #   ports:

  #     - 5432:5432

  react2:
    image: khaashifriaz/react2:v1
    container_name: react2
    ports:
      - 5002:3000
    environment:
      - DB_HOSTNAME=gigstr-db-container
      - DB_PASSWORD=gigstr

  api2:
    image: khaashifriaz/api2:v1
    container_name: api2
    ports:
      - 3002:3000
    environment:
      - DB_HOSTNAME=gigstr-db-container
      - DB_PASSWORD=gigstr

  react3:
    image: khaashifriaz/react3:v1
    container_name: react3
    ports:
      - 5003:3000
    environment:
      - DB_HOSTNAME=gigstr-db-container
      - DB_PASSWORD=gigstr

  api3:
    image: khaashifriaz/api3:v1
    container_name: api3
    ports:
      - 3003:3000
    environment:
      - DB_HOSTNAME=gigstr-db-container
      - DB_PASSWORD=gigstr
