name: Docker React CI

on:

  push:

    branches: [ main ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:

    - uses: actions/checkout@v2

    - name: Login to DockerHub
      run: echo ${{ secrets.DOCKER_PASS }} | docker login -u ${{ secrets.DOCKER_USER }} --password-stdin
      working-directory: actcept

    - name: Build the Docker image
      run: docker build -t khaashifriaz/react1:v1 .
      working-directory: actcept

    - name: Push the docker image
      run: docker push khaashifriaz/react1:v1
      working-directory: actcept