name: Docker Image CI

on:
  push:
    branches: [ main ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Login to DockerHub
      run: echo ${{ secrets.DOCKER_PASS }} | docker login -u ${{ secrets.DOCKER_USER }} --password-stdin

    - name: Build the Docker image
      run: docker build -t khaashifriaz/gigstr:gigtag .

    - name: Push the docker image
      run: docker push khaashifriaz/gigstr:gigtag

    # - name: Remove old container
    #   run: docker rm --force CONTAINER 'gigstr-db-container'

    # - name: Run new docker container
    #   run: docker run -d --name gigstr-db-container -p 5432:5432 khaashifriaz/gigstr:gigtag
